#include <cstdio>
#include <string>	
#include <vector>
#include <iostream>
#include <algorithm>
#include <filesystem>
#include <chrono>
#include <utility>
#include <windows.h>
#include <string>
#include <array>
#include <locale>
#include <codecvt>
#include <string_view>